FROM python:3.8

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .
ARG PYMONGO_VERSION
RUN pip install pymongo==$PYMONGO_VERSION

EXPOSE 5000

ENV APP_SETTINGS=config.DevConf

CMD ["python", 	"app.py"]