version: "3.8"


services:
  web-app:
    image: flask-image
    build:
      context: .
      dockerfile: Dockerfile.flask
      args:
        PYMONGO_VERSION: ${VERSION}
    env_file:
      - flask.env
    ports:
      - 8000:5000
    volumes:
      - ${PWD}:/app
  
  mongodb:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
    - mongo:/data/db
      
volumes:
  mongo:
  

